data_format: 'yaml'
show_analysis_time: False
show_analysis_paths: False

report_header_info:
  - Contact E-mail: 'trex_info@cornell.edu'
  - Reference Genome: !ENV "${MQC_GENOME}"
custom_logo_url: https://trex.biotech.cornell.edu/
plots_force_interactive: True


table_sample_merge:
  deduplicated : "DEDUP"
  primary : "primary"
  dupMarked : "dupMarked"


table_column_name:
  BamQC:
    percentage_aligned: "BamQC %"


