data_format: 'yaml'
show_analysis_time: False
show_analysis_paths: False

report_header_info:
  - Contact E-mail: 'trex_info@cornell.edu'
  - Reference Genome: !ENV "${MQC_GENOME}"
custom_logo_url: https://trex.biotech.cornell.edu/
plots_force_interactive: True


table_sample_merge:
  deduplicated : "DEDUP"
  primary : "primary"
  dupMarked : "dupMarked"

table_sample_merge:
  deduplicated : "DEDUP"
  primary : "primary"
  dupMarked : "dupMarked"


table_columns_visible:
  qualimap_bamqc-1_x_pc: true
  qualimap_bamqc-5_x_pc: true
  qualimap_bamqc-10_x_pc: true
  fastp-after_filtering_q30_rate: true
  qualimap_bamqc-percentage_aligned : false


table_columns_name:
  qualimap_bamqc-percentage_aligned : "% Reads Processed: qualimap:bamqc"