FROM mambaorg/micromamba:1.5.8

USER root

RUN micromamba install -y -n base -c bioconda -c conda-forge \
    fastp \
    bowtie2 \
    samtools \
    picard \
    && micromamba clean -afy

ENV PATH="/opt/conda/bin:$PATH"
